### ISSUE TITLE
Order should allow zero LineItems?

### ISSUE THREAD

**Issue by oyeb** [aviabird/snitch#43]
~~Creating~~ Updating an order ~~without~~ by removing its `LineItem`s fails because of the way we compute `order.total`:
```
** (Enum.EmptyError) empty error
    (elixir) lib/enum.ex:1855: Enum.reduce/2
    (snitch_core) lib/core/data/schema/order.ex:92: Snitch.Data.Schema.Order.compute_totals/1
    (snitch_core) lib/core/tools/helpers/query_helper/query_helper.ex:37: Snitch.Tools.QueryHelper.update/4
```
This is also related to the way we handle money.

1. The order total is the sum of `line_item.total` (if they are all in the same currency, the other case is not handled).
2. Order schema sets the default price to `#Money<0, :USD>`, but why `USD`?
    a. We should probably pick the "default" curreny from application config.
    b. Does it matter which currency it is? Zero in all currencies is the same :smile: 
3. When we have no `line_items`, The `order.total` must be set to zero... but in which currency?

There are 2 issues here:
1. Should we allow setting an Order's line_items to `[]`?
2. Decide what to do about the default currency.

**Comment by oyeb** [comment]
To update an order, we have `Model.Order.update` -- and this function requires a non-empty `line_items` in it's `params`. If the `line_items` is `[]`, it will attempt to delete all line_items (and fail as described above).

A workaround is to call it like this:
```elixir
params = %{} # updates for order fields
Model.order.update(Map.put(params, :line_items, order.line_items), order)
```
to retain the existing line_items and update only other fields.

Thus, we can add `Model.Order.update_line_items` that behave like the existing `update` and,
`Model.Order.update` can be upgraded with the workaround, to allow updating other fields.

**Comment by oyeb** [comment]
Spree does not allow `line_items` to become empty AFAICS in their [state machine](https://github.com/spree/spree/blob/master/core/app/models/spree/order/checkout.rb#L90).

That said, the `order_updater.rb` module [seems to be resilient](https://github.com/spree/spree/blob/master/core/app/models/spree/order_updater.rb#L96) to empty `line_items` because in that case `item_total` is set to zero. We can't simply set it to zero because we need the currency too :disappointed:

**Comment by oyeb** [comment]
1. We allow setting an Order's line items to `[]`, by expecting a default currency in the application config.
2. The default currency will be fetched by `snitch_core` from the application config.
